# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 45effd117a3208b271ee11d4656426bd153c443ed3e5d570a48307b2a84e15272dbb6ef3218939ce78796b1675c63ff0e55f9c22d59113e75bb241db5ef8177b

test:
  secret_key_base: 132e8200a55ae7606bff956c0b9073bd7c9e2efd34af6e3d7d81d51ceb3ee5b08f58d23c4171e4e93e9090d368511d2ab2d88332e1cd80e6cf983ea3e24cf301

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
